[package]
name = "scalp_macro"
version = "0.1.0"
authors = ["Magicolo <magicololand@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "*"
quote = "*"
scalp_core = { path = "../scalp_core" }